import c from './attachment.js';
import f from './cookie.js';
import d from './date.js';
import m from './decode.js';
import p from './delta.js';
import l from './ids.js';
import i from './message.js';
import g from './presence.js';
import u from './readTyp.js';
import x from './thread.js';
import * as D from './utils.js';
const n = { default: c },
  T = { default: f },
  h = { default: d },
  y = { default: m },
  o = { default: p },
  a = { default: l },
  r = { default: i },
  t = { default: g },
  s = { default: u },
  P = { default: x },
  e = D,
  _ = e.getType,
  M = e.formatID,
  R = e.padZeros,
  I = e.arrayToObject,
  A = e.arrToForm,
  C = e.getData_Path,
  k = e.setData_Path,
  v = e.getPaths,
  E = e.cleanHTML,
  b = e.getCurrentTimestamp,
  F = e.getSignatureID,
  H = a.default.generateOfflineThreadingID,
  O = a.default.generateThreadingID,
  j = a.default.getGUID,
  G = a.default.generateTimestampRelative,
  L = h.default.formatDate,
  S = t.default.presenceEncode,
  U = t.default.presenceDecode,
  Z = t.default.generatePresence,
  $ = t.default.generateAccessiblityCookie,
  q = t.default.formatProxyPresence,
  w = t.default.formatPresence,
  z = n.default._formatAttachment,
  B = n.default.formatAttachment,
  J = o.default.getAdminTextMessageType,
  K = o.default.formatDeltaEvent,
  N = o.default.formatDeltaMessage,
  Q = o.default.getMentionsFromDeltaMessage,
  V = o.default.formatDeltaReadReceipt,
  W = r.default.formatMessage,
  X = r.default.formatEvent,
  Y = r.default.formatHistoryMessage,
  ee = s.default.formatReadReceipt,
  te = s.default.formatRead,
  oe = s.default.formatTyp,
  ae = P.default.formatThread,
  re = y.default.decodeClientPayload,
  se = T.default.formatCookie;
var xe = {
  getType: _,
  formatID: M,
  padZeros: R,
  arrayToObject: I,
  arrToForm: A,
  getData_Path: C,
  setData_Path: k,
  getPaths: v,
  cleanHTML: E,
  getCurrentTimestamp: b,
  getSignatureID: F,
  generateOfflineThreadingID: H,
  generateThreadingID: O,
  getGUID: j,
  generateTimestampRelative: G,
  formatDate: L,
  presenceEncode: S,
  presenceDecode: U,
  generatePresence: Z,
  generateAccessiblityCookie: $,
  formatProxyPresence: q,
  formatPresence: w,
  _formatAttachment: z,
  formatAttachment: B,
  getAdminTextMessageType: J,
  formatDeltaEvent: K,
  formatDeltaMessage: N,
  getMentionsFromDeltaMessage: Q,
  formatDeltaReadReceipt: V,
  formatMessage: W,
  formatEvent: X,
  formatHistoryMessage: Y,
  formatReadReceipt: ee,
  formatRead: te,
  formatTyp: oe,
  formatThread: ae,
  decodeClientPayload: re,
  formatCookie: se,
};
export {
  z as _formatAttachment,
  A as arrToForm,
  I as arrayToObject,
  E as cleanHTML,
  re as decodeClientPayload,
  xe as default,
  B as formatAttachment,
  se as formatCookie,
  L as formatDate,
  K as formatDeltaEvent,
  N as formatDeltaMessage,
  V as formatDeltaReadReceipt,
  X as formatEvent,
  Y as formatHistoryMessage,
  M as formatID,
  W as formatMessage,
  w as formatPresence,
  q as formatProxyPresence,
  te as formatRead,
  ee as formatReadReceipt,
  ae as formatThread,
  oe as formatTyp,
  $ as generateAccessiblityCookie,
  H as generateOfflineThreadingID,
  Z as generatePresence,
  O as generateThreadingID,
  G as generateTimestampRelative,
  J as getAdminTextMessageType,
  b as getCurrentTimestamp,
  C as getData_Path,
  j as getGUID,
  Q as getMentionsFromDeltaMessage,
  v as getPaths,
  F as getSignatureID,
  _ as getType,
  R as padZeros,
  U as presenceDecode,
  S as presenceEncode,
  k as setData_Path,
};

// ─── Plugin Descriptor ──────────────────────────────────────────
/** @type {import('./plugin-provider.js').FcaPlugin} */
export const $plugin = {
  name: 'fca-utils-format-index',
  meta: { category: 'utils', path: 'lib/utils/format/index.js' },
  setup(_ctx) {
    // provides: _formatAttachment, arrToForm, arrayToObject, cleanHTML, decodeClientPayload, formatAttachment, formatCookie, formatDate
  },
};
